name: Gitconvex Server pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install --global jest
      - run: mkdir -p ./database && touch ./database/repo-datastore.json
      - run: echo '[{"databaseFile":"./database/repo-datastore.json","port":9001,"commitLogDatabase":"./database/commitLogs.sqlite"}]' > ./env_config.json
      - run: echo '[{"id":"1593690333568","repoName":"JEST_REPO","repoPath":"."}]' > ./database/repo-datastore.json
      - run: npm run test
      - name: Droplet commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            sh /opt/workroom/github-deploy.sh gitconvex-server
